desc 'Program na vykresleni aktivni zony'
task :all do
	
	# Nacteni sestiny AZ z textoveho souboru
	list = {}
	i = 0
	IO.foreach("./Zadani/text_kart.txt") do |line|
		list[i] = "#{line}".split
		i += 1
	end
	
	# Vypis nazvu do terminalu pro kontrolu
	list.each do |i, name|
		puts "#{i} => #{name}"
	end
	
	# Prirazeni barev jednotlivym clankum pro poydejsi vyuyiti
	ary = []
	list.each do |i, name|
		size = name.length
		(0..size-1).each do |j|
			ary << name[j]
		end
	end
	
	names = ary.uniq
	
	colors = {}
	(0..names.length-1).each do |i|
		colors["#{names[i]}"] = "#%06x" % (rand * 0xffffff)
	end
	
	# Vykresleni svg souboru Kartogram.svg
	a = 27		# hrana sestiuhelniku
	f = File.open("Kartogram.svg", 'w')
	f.puts %{<svg  xmlns="http://www.w3.org/2000/svg"
					xmlns:xlink="http://www.w3.org/1999/xlink">}
	list.each do |i, name|
		size = name.length
		trans = 10.1
		x_origin = (list[0].length+1/2)*a*Math.sqrt(3)
		y_origin = 3*a/2+trans*a
		(0..5).each do |k|
			f.puts %{ <g transform="rotate(#{k*60}, #{x_origin}, #{y_origin})"> }
			(1..size).each do |j|
				color = colors.find{|key,v| key.include? "#{name[j-1]}" }.last
				if name[j-1] == "*"
					width = 0
					pin = ""
					opacity = 0
				else
					width = 1.5
					pin = "#{name[j-1]}"
					opacity = 1
				end
				f.puts %{ <g transform = "translate(#{j*a*Math.sqrt(3)+i*a*Math.sqrt(3)/2} #{(i+1)*3*a/2})">
							<polygon fill = "#{color}" stroke = "black" stroke-width = "#{width}" fill-opacity = "#{opacity}"
								points = "	#{-a*Math.sqrt(3)/2},#{a/2+trans*a}
											#{0},#{a+trans*a}
											#{a*Math.sqrt(3)/2},#{a/2+trans*a}
											#{a*Math.sqrt(3)/2},#{-a/2+trans*a}
											#{0},#{-a+trans*a}
											#{-a*Math.sqrt(3)/2},#{-a/2+trans*a}" />
							<text transform = "rotate(#{-k*60}, #{0}, #{trans*a})" text-anchor = "middle" x = "#{0}" y = "#{trans*a}" style = "fill:#000000;font-size:12.0;font-weight:bold;">#{pin}</text>
							</g>
						}
			end
			f.puts %{ </g> }
		end
	end
	f.puts %{</svg>}
	f.close
end