require 'date'
task :data do
  `rm data/*.csv`
  units = {}
  (1..50).each do |i|
    npp = %w{Disneyland Atlantis CandyMountain}.sample
    units[npp] ||= 0
    units[npp] += 1

    d1 = lambda do |da|
      y,m,d = da.year, da.month, da.day
      "%04d-%02d-%02d" % [y,m,d]
    end
    d2 = lambda do |da|
      y,m,d = da.year, da.month, da.day
      "%02d/%02d/%04d" % [m,d,y]
    end
    d3 = lambda do |da|
      y,m,d = da.year, da.month, da.day
      "%d.%d.%d" % [d,m,y]
    end

    columns = [:bc, :ao, :fha].shuffle
    da = Date.civil(1980+rand(20), 1+rand(12), 1+rand(25))
    bc = 5+rand*2
    fha = 1.3+rand*0.2
    ao = -8+rand*3
    f = File.open("data/data#{i}.csv", 'w')
    f.puts "##{npp} NPP, unit #{units[npp]}"
    f.puts "#date;#{columns.map(&:to_s).join(";")}"
    dx = [d1,d2,d3].sample
    n = 0
    loop do
      n += 1
      y,m,d = da.year, da.month, da.day
      date = dx[da]
      f.print date
      columns.each do |v|
        f.print ";", eval(v.to_s).round(3)
      end
      f.puts
      bc -= 0.01*(0.5+rand)
      ao += 0.01*(0.5+rand)/n**0.3
      fha -= 0.001*(0.5+rand)
      da += 1
      break if bc < 0
    end
  end
end